# Creación de Numpy Arrays

Para importar **NumPy** la comunidad a definido hacerlo como `import numpy as np`, es mas por buenas prácticas y eficiencia al momento de escribir código.]

In [1]:
import numpy as np

## Crear un ndArrya

Existen muchas maneras de crear **ndArray** con **NumPy** a continuación te mostrare algunos de ellos.

> debes de tener en cuenta que al crear un array este debe de ser del mismo tipo de dato

In [2]:
np.array([1, 2, 3, 4, 5, 3]) # array de Int

array([1, 2, 3, 4, 5, 3])

In [4]:
np.array([3.14, 1, 2, 4, 5]) # array de Floats

array([3.14, 1.  , 2.  , 4.  , 5.  ])

Si intentaramos crear un array con un string dentro?

In [6]:
np.array([1, 3, 4, '5', 4])

array(['1', '3', '4', '5', '4'], dtype='<U11')

Mira que el resultado es un array de solo strings, no contiene multiples tipos de datos como lo haría una lista normal de Python.

### definir el tipo de dato

Sin embargo numpay nos permite definir el tipo de dato que va a contener el array recien creado, esto lo ahcemos con el atributo **dtype** al momento de crearlo

In [14]:
np.array([1, 2, 3, 4, 5, 3], dtype='int32') # array de Int

array([1, 2, 3, 4, 5, 3])

In [16]:
np.array([1, 2, 3, 4, 5, 3], dtype='float32') # array de Int

array([1., 2., 3., 4., 5., 3.], dtype=float32)

Fíjate que el tipo de dato definido esta entre comillas y hace referencia a un tipo de dato de **C** no de **Python**

### Creando arrays desde funciones

**Numpy** por defecto nos permite crear arrays de ciertos valores comop por ejemplo de ceros, o unos o incluso numeros random, vamos a ver algunos de ellos

In [18]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.96088079, 0.37822325, 0.85586973],
       [0.76157359, 0.22341071, 0.47404005],
       [0.84743883, 0.10154132, 0.90660617]])

In [25]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.19386955,  0.75489863, -0.4124827 ],
       [ 0.49057589, -0.15374593,  0.13118604],
       [ 0.71453134, -1.39834409,  0.61793699]])

In [26]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 5, 4],
       [4, 3, 7],
       [8, 1, 2]])

In [27]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])