# ndArray: Multidimensional Array Object

Uno de los objetos clave dentro de **Numpy** son los arreglos multidimensionales o **ndArray** que son arreglos basados en C que cuentan con las siguientes características

- Ocupan un espacio de memoria continuo, es decir que no estas distribuidos sobre la memoria, por lo que son más fáciles de acceder
- Son de un mismo tipo de dato, lo cual mejora el performance de la memoria ya que se sabe el tamaño de cada elemento

> El importar `numpy` como `np` es una convención recomendada para evitar que `numpy` sobrescriba definiciones del core de Python como `max` y `min`

In [2]:
import numpy as np

In [3]:
data = np.array([[1,3,4,5], [-2, 3,-1, 9]])

data

array([[ 1,  3,  4,  5],
       [-2,  3, -1,  9]])

hemos creado el arreglo `data` que es una matriz de **2x4** elementos de los arreglos siempre deben de sert simetricos, es decir que no podemos crear un arreglo en donde un elemento es otro arreglo de 3 elementos y otro de 4

> si solo escribimos el nombre de la variable como ultimo valor de la ejecución del bloque de código, el valor que contiene se imprimira en cosola

### Creacion de ndArrays

existen varias funciones dentro de **Numpy** que nos permiten crear arreglos de este tipo, pero antes debemos de definir que existen dos tipos de elementos en las matematicas que pueden ser representados con arreglos de numpy

- vectores -> los vectores son arreglos de una fila y n elementos
- matrices -> las matrices son arreglos de `n x m` elementos
- matrices multidimensionales -> son matrices de matrices pueden tener diferentes niveles de profundidad

> en todos los casos es importante resaltar y mantener la simetria enrte los elemento de estos objetos

a continuación los métodos de creación de arreglos

| función | descripción |
|---------|-------------|
|array    |Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default|
|asarray  | Convert input to ndarray, but do not copy if the input is already an ndarray|
|arange|Like the `built-in` range but returns an ndarray instead of a list|
|ones, ones_like|Produce an array of all 1s with the given shape and data type; `ones_like` takes another array and produces a `ones` array of the same shape and data type|
|zeros, zeros_like|Like `ones` and `ones_like` but producing arrays of 0s instead|
|empty, empty_like|Create new arrays by allocating new memory, but do not populate with any values like `ones` and `zeros`|
|full, full_like| Produce an array of the given shape and data type with all values set to the indicated “fill value”; `full_like` takes another array and produces a filled array of the same shape and data type|
|eye, identity| Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)|

In [4]:
data1 = [6,7.5,8.9,1]

# podemos crear arreglos a partir de otros objetos iterables de Python como lo es una lista
arr_1 = np.array(data1)
arr_1

array([6. , 7.5, 8.9, 1. ])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr_2 = np.array(data2)
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr_3 = np.arange(10)
arr_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr_4 = np.identity(3)
arr_4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

una vez tienes creado el objeto de ndArray puedes ver información relevante del objeto como por ejemplo el tipo de dato almacenado, la dimension, etc.

In [8]:
print("arr_2 shape:",arr_2.shape)
print("arr_2 size:",arr_2.size)
print("arr_2 ndim:",arr_2.ndim)
print("arr_2 dtype:",arr_2.dtype)

arr_2 shape: (2, 4)
arr_2 size: 8
arr_2 ndim: 2
arr_2 dtype: int64


### Tipos de datos de un ndArray

Dentro de los tipos de datos que podemos asignarle a un ndArray encontramos

|Type|Type code|Description|
|----|---------|-----------|
|int8, uint8|i1, u1|Signed and unsigned 8-bit (1 byte) integer types|
|int16, uint16|i2, u2|Signed and unsigned 16-bit integer types|
|int32, uint32|i4, u4|Signed and unsigned 32-bit integer types|
|int64, uint64|i8, u8|Signed and unsigned 64-bit integer types|
|float16|f2|Half-precision floating point|
|float32|f4 or f|Standard single-precision floating point; compatible with C float|
|float64|f8 or d|Standard double-precision floating point; compatible with C double and Python float object|
|float128|f16 or g|Extended-precision floating point|
|complex64, complex128, complex256|c8, c16, c32|Complex numbers represented by two 32, 64, or 128 floats, respectively|
|bool|?|Boolean type storing True and False values|
|object|O|Python object type; a value can be any Python object|
|string_|S|Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use 'S10'|
|unicode_|U|Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')|

Debemos de tener en cuenta que al momento de crear un arreglo este solo puede contener un tipo de dato, y nostros podemos definirlo al momento de crearlo, como en los siguientes ejemplos


In [9]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [11]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [12]:
float_arr.dtype

dtype('float64')