# Aritmetica con Arreglos multidimensionales

La ventaja de los arreglos de Numpy es que se comportan según la aritmetica de arreglos de algebra, es decir que

- Podemos sumar/restar matrices de las mismas dimensiones y este se hara uno a uno
- podemos multiplicar arreglos de mismas dimensiones N x M = M x N
- Podemos dividir/multiplicar escalares por las matrices y esto aplicará a cada elemento del arreglo

Veamos algnos ejemplo

In [1]:
import numpy as np

In [2]:
# Multiplicación de matrices
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
# Suma/Resta de matrices
print(arr + arr)
arr - arr

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# En el caso de Escalares tenemos el siguiente comportamiento
print(arr * 3)
print(1 / arr)

[[ 3.  6.  9.]
 [12. 15. 18.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


También podemos aplicar operaciones que den como resultado una matriz booleana

In [6]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [7]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])