# Indexación y Slicing en arreglos multidimensionales

La indexación de los arreglos de numpy siguen el mismo patros de Python y de la notación matematica, es decir que podemos acceder a sus elementos con la notación `arr[x][y]` asi como podriamos hacer `arr[x, y]`, y asi susecivamente a medida que se tenga arreglos de mayor tamaño y longitud

In [1]:
import numpy as np

In [5]:
arr = np.arange(10)
print('arr -> ',arr)
print('arr[5] -> ',arr[5])
print('arr[5:8] -> ',arr[5:8])

arr ->  [0 1 2 3 4 5 6 7 8 9]
arr[5] ->  5
arr[5:8] ->  [5 6 7]


podemos modificar los elementos de los arreglos de uno en uno o de una sola tanda

In [7]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

> Los Arreglos en Numpay se tratan por referencia, es decir que cuando se hace un slice o se modifican los elementos del mismo, se hacen directamente en el objeto original, para compiarlos debes de usar el método `copy()` de los arreglos, pero debes de tener en cuenta el performance que esto implica, ya que los arreglos de Numpy estan hechos pensados en el procesamiento de datos

In [9]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [10]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

## Indexación con Slicing

es posible obtener secciones de los arreglos a traves de los slicing, el concepto es similar al de una sola dimensión solo que extrapolado cada dimensión, veamos un ejemplo de su uso

In [12]:
print(arr)
print(arr[1:6])

[    0     1     2     3     4    12 12345    12     8     9]
[ 1  2  3  4 12]


In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('arr2d ->\n', arr2d)
print('arr2d[:2] ->\n', arr2d[:2])

arr2d ->
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2] ->
 [[1 2 3]
 [4 5 6]]


## Indexación con arreglos Booleanos

Una de las ventajas de los arreglos de numpy es que nos permite, selecionar los elementos de usando matrices de igual dimension pero cuyo typo de dato es booleano, de esta forma podemos aprovechar los aperadores booleanos que se aplican a las matrices

In [18]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [19]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [20]:
# podemos obtener del arreglo de nombres todos aquellos que sean Bob
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [21]:
# podemos usar este arreglo booleano para indexar el arreglo de datos
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

> Para poder hacer el anterior ejemplo fijate que las matrices tienen la misma longitud en su primera dimensión

De igual manera podemos combinar el indexado bolleano junto con el slicing para obtenes mas control o filtrar mejor nuestros datos

In [24]:
data[names == "Bob", 1]

array([7, 0])

In [25]:
# Podemos usar el operador ~ como una negación
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [26]:
# De igual manera tenemos el operador OR (|) o AND (&) con las mascaras booleanas de los arreglos
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [28]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [30]:
# Tambien puedes usar la indexación booleana para modificar valores
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [32]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])