# Introducción a NumPy

`NumPy` (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers

> In some ways, `NumPy` arrays are like Python’s `built-in` list type, but `NumPy` arrays provide much
more efficient storage and data operations as the arrays grow larger in size

## Manejo de datos en NumPy y Python

> NumPy  son paquetes y librerías desarrolladas en C para manipular arrays

Una de las principales razones por la que Numpy es mas eficiente que los tipos base de Python para procesar datos como las listas, es la forma en que se procesan los datos, por ejemplo en Python al ser de tipado dinámico, las variables lo que almacenan son posiciones de memoria, que muchas veces no están en orden, simplemente esta en donde se le permitan crear , por el contrario C si permite reservar el espacio de memoria para una variable y nunca cambiara mientras esta viva, mientras que en Python si cambiará cada vez que se reasigne por un valor inmutable

![alt](./images/img6.png)

Lo mismo sucede con las listas de Python, que lo que guarda es un arreglo de apuntadores, cuyo valores varían según la posición de memoria

![alt](./images/img7.png)

Esa es la principal diferencia de NumPy (lenguaje C) con Python, es mucho mas eficiente, sin embrago manejar se es mucho mas complejo que Python, por lo que todo ese proceso es abstracto a nosotros

## Tipos de datos en Numpy

Aunque muchas veces numpy creara el arreglo con el tipo de dato mas apropiado, es posible asignarle este dato por defecto como ya vimos en los ejemplos anteriores, sin embargo es bueno conocer los tipos de datos existentes

![alt](./images/img8.png)

Para importar **NumPy** la comunidad a definido hacerlo como `import numpy as np`, es mas por buenas prácticas y eficiencia al momento de escribir código.]



In [1]:
import numpy as np

## Crear un ndArrya

Existen muchas maneras de crear **ndArray** con **NumPy** a continuación te mostrare algunos de ellos.

> debes de tener en cuenta que al crear un array este debe de ser del mismo tipo de dato

In [2]:
np.array([1, 2, 3, 4, 5, 3]) # array de Int

array([1, 2, 3, 4, 5, 3])

In [3]:
np.array([3.14, 1, 2, 4, 5]) # array de Floats

array([3.14, 1.  , 2.  , 4.  , 5.  ])

Si intentaramos crear un array con un string dentro?

In [4]:
np.array([1, 3, 4, '5', 4])

array(['1', '3', '4', '5', '4'], dtype='<U11')

Mira que el resultado es un array de solo strings, no contiene multiples tipos de datos como lo haría una lista normal de Python.

### definir el tipo de dato

Sin embargo numpay nos permite definir el tipo de dato que va a contener el array recien creado, esto lo ahcemos con el atributo **dtype** al momento de crearlo

In [5]:
np.array([1, 2, 3, 4, 5, 3], dtype='int32') # array de Int

array([1, 2, 3, 4, 5, 3])

In [6]:
np.array([1, 2, 3, 4, 5, 3], dtype='float32') # array de Int

array([1., 2., 3., 4., 5., 3.], dtype=float32)

Fíjate que el tipo de dato definido esta entre comillas y hace referencia a un tipo de dato de **C** no de **Python**

### Creando arrays desde funciones

**Numpy** por defecto nos permite crear arrays de ciertos valores comop por ejemplo de ceros, o unos o incluso numeros random, vamos a ver algunos de ellos

In [7]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.86291308, 0.71619663, 0.87467665],
       [0.69011952, 0.89173088, 0.06788066],
       [0.08275653, 0.88325293, 0.86624946]])

In [13]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-2.65910936, -1.4526688 ,  1.04049815],
       [ 1.72312802,  0.31626186, -2.41112692],
       [-0.52933928,  0.74743961, -0.63594529]])

In [14]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 6, 7],
       [9, 2, 5],
       [4, 4, 2]])

In [15]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])