# Computación con Numpy: Universal Functions

Las funciones universales de Numpy son funciones built-in que normalmente permiten realizar las tareas mas comunes y usadas en el procesamiento de datos, como lo son suma, max, min, desviación estándar, etc.

Aunque los arreglos y otros objetos de Numpy tienen sus propios métodos para realziar este tipo de operación, el uso de las funciones universales (uFuctions) es recomendado ya que están mucho mas optimizados por lo que la velocidad de procesamiento será mucho mayor para los arreglos que son pasados como parámetros

> Son incluso mas optimisados que el for loop y los métodos de cada array

Comparemos las una **uFunction** con una función implementada con un ciclo for

In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)

%timeit compute_reciprocals(values)
%timeit 1 / values

23.5 µs ± 2.62 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.42 µs ± 72.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Puedes observar la diferencia en tiempos de ejecución de un método a otro? ahora imaginate que no procesas un arreglo de 5 valores sino de miles

Miremos cuales son las **uFunctions** báscias

In [5]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


Todas estas funciones estan implementadas en Numpy como se muestran en la siguiente imagen, solo que Python permite utilizar la sintaxis mas amigable al usar solamente los signos operadores

> El modo de funcionar es muy parecido al funcionamiento de los arreglos y vectores en algebra líneal

![funciones de numpy](./images/img1.png)


También disponemos de funciones un poco mas avanzadas relacionadas con matematica y estadistica

In [6]:
# VALOR ABSOLUTO
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

Funciones Trigonometricas, aqui cabe resaltar que las funciones aunque son **uFunctions** no tiene su operador asociado como + o *, sino que se llaman directamente a través del módulo de numpy que por buenas prácticas es np

In [9]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


También tenemos funciones exponenciales y logaritmicas

In [14]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]
exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


Aunque Numpy trae una amplia variedad de funciones también podemos importar funciones de otros modulos como lo es **SciPy**, un paquete ampliamente usado para analizar y procesar información

In [16]:
from scipy import special

# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [17]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


# Caracteristicas avanzadas de UFunctions

A medida que vas trabajando con funciones universales, vas a ir descubriendo caracteristicas muy poderosas que te permitirar optimizar aun mas tu código, por ejemplo

1. Specifying output: esta caracteristica te permite definir en donde se almacenara el resultado del procesamiento o calculos realizados, estoy nos permite tener la variable final apartada en meoria y no se ahce uso de una varibale temporal para el procesamiento

In [18]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


También podemos llenar ciertos espacios de un arreglo ya creado

In [19]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


## Obtener valores o información del arreglo

In [20]:
# calling reduce on the add ufunc returns the sum of all elements in the array
x = np.arange(1, 6)
np.add.reduce(x)

15

In [23]:
# calling reduce on the multiply ufunc results in the product of all array elements
np.multiply.reduce(x)

120

In [26]:
# If we’d like to store all the intermediate results of the computation, we can instead use accumulate
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [27]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

More information on universal functions (including the full list of available functions) can be found on the NumPy and SciPy documentation websites.

Recall that you can also access information directly from within IPython by importing the packages and using IPython’s tab-completion and help (?)